Travis-ci build draft #35

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,17 +33,17 @@ before_deploy:
   - composer update --no-dev
   - sed -i -r "s/(VERSION.*)(@git_tag@)/\1$VERSION/" bin/createDetailsFile.php
   - box compile
+  - mkdir $VERSION
   # Prepare release information
-  - |
-    if [[ "master" == "$TRAVIS_BRANCH" ]];
-    then
-      #[[ -n `git tag | grep $VERSION` ]] && { echo "Error: cannot deploy to master because current tag already exists."; exit 1 }
-      NOTES="`cat CHANGELOG.md | sed -r '0,/^## \['$VERSION'\]/d' | sed -r '/^\s*$/,$d'`"
-    else
-      VERSION="$VERSION-`date +%s%3N`"
-      NOTES="Development build deployed on `date +%F-%T`"
-      export GITHUB_PRERELEASE="true"
-    fi
+  - if [[ "master" == "$TRAVIS_BRANCH" ]];
+  - then
+  -   #[[ -n `git tag | grep $VERSION` ]] && { echo "Error: cannot deploy to master because current tag already exists."; exit 1 }
+  -   NOTES="`cat CHANGELOG.md | sed -r '0,/^## \['$VERSION'\]/d' | sed -r '/^\s*$/,$d'`"
+  - else
+  -   VERSION="$VERSION-`date +%s%3N`"
+  -   NOTES="Development build deployed on `date +%F-%T`"
+  -   export GITHUB_PRERELEASE="true"
+  - fi
   # Save deployment values
   - export TRAVIS_TAG="$VERSION"
   - export GITHUB_NAME="$VERSION"
