travis.yml: refactor out multi-line commands

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,19 +41,11 @@ before_deploy:
   # Generate version number without leading 'v'
   - NUM_VERSION="${VERSION/#v/}"
   # Prepare release information
-  - |
-    if [[ "master" == "$TRAVIS_BRANCH" ]]
-    then
-      [[ -n `git tag | grep $VERSION` ]] && { echo "Error: cannot deploy to master because current tag already exists."; exit 1 }
-      NOTES="`cat CHANGELOG.md | sed -r '0,/^## \['$NUM_VERSION'\]/d' | sed -r '/^\s*$/,$d'`"
-    fi
-  - |
-    if [[ "master" !== "$TRAVIS_BRANCH" ]]
-    then
-      VERSION="$VERSION-`date +%s%3N`"
-      NOTES="Development build deployed on `date +%F-%T`"
-      export GITHUB_PRERELEASE="true"
-    fi
+  # Development
+  - [[ "master" !== "$TRAVIS_BRANCH" ]] && { VERSION="$VERSION-`date +%s%3N`"; NOTES="Development build deployed on `date +%F-%T`"; export GITHUB_PRERELEASE="true" }
+  # Production
+  - [[ -n `git tag | grep $VERSION` ]] && { echo "Error: cannot deploy release because current tag already exists."; exit 1 }
+  - [[ -z "$NOTES" ]] && NOTES="`cat CHANGELOG.md | sed -r '0,/^## \['$NUM_VERSION'\]/d' | sed -r '/^\s*$/,$d'`"
   # Build package and binaries
   - composer update --no-dev --optimize-autoloader
   - sed -i -r "s/(VERSION.*)(@git_tag@)/\1$NUM_VERSION/" bin/createDetailsFile.php
